### ISSUE TITLE
Perform a team design workshop to improve the Dashboard

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#206]
Currently there are some issues related to the design of the `Dashboard` page:

- [ ] remove view of individual VMs from dashboard #188
- [ ] in dashboard, provide global run list #187
- [ ] As a user, I can select multiple runs in the dashboard and perform actions on them. #186
- [ ] in the dashboard, move tags to beginning of run display table #185

We should think of them as a whole instead of isolated arbitrary changes. I suggest we should sit down and thoughtfully re-design the Dashboard page, in the same productive way that we did to focus on streamline, speed-up and enhance the user onboarding experience.
