### ISSUE TITLE
Adapt Alice tour to be used in new webapp structure

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#456]
## Upstream dependencies

- [x] make dashboard the welcome page #423
- [x] Make Dashboard the welcome page. slipstream/SlipStreamServer#485

## Downstream dependencies

- [x] The last step in the Alice's tour is not shown. #425
